item_name = str("Name: Polo Shirt")
item_sku = str("SKU: PO-TS-34-BK")
item_quantity = str("Quantity: 50")
item_price = str("Price: £ 50.00")
name = input("Enter your name: ")
address = input("Enter your address: ")
item = input("Enter the your item: ")
print("Store")
print("Name: ", name)
print("Address ", address)
print("Items: ", item_name, item_sku, item_quantity, item_price)